### ISSUE TITLE
[Bug] User seeds not adding first and last name

### ISSUE THREAD

**Issue by AGorinam** [wyshlist/wyshlist#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Generate a bunch of additional users.
`99.times do |n|`
    `name = Faker::Name.name`
    `email = Faker::Internet.email`
    `password = "123123"`
    `User.create!(email: email, password: password, username: name)`
    `print "*"`
`end`

**Comment by christinasugiono** [comment]
We might need to add organization to all the users too
