### ISSUE TITLE
constraint on subdomain organizations#show page not working

### ISSUE THREAD

**Issue by christinasugiono** [wyshlist/wyshlist#164]
**Describe the bug**
the organization id should be the same as the subdomain name
organizations#show was mentioned twice in the routes

<img width="1251" alt="Screenshot 2023-08-11 at 13 23 56" src="https://github.com/wyshlist/wyshlist/assets/74747669/f93aa7db-7161-4e8b-bb99-7731e7e22577">

**Comment by Danrod16** [comment]
@christinasugiono I'm looking at this as well as part of this issue #159 and looking at this tutorial to fix it: 

https://gorails.com/episodes/domain-subdomain-routing-constraints-in-rails

We'll try to constraint the roots and it's environment to the subdomain 🤟
